// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9_EiUIW4Uk_gi9mnyQR2JQ52D_KiFvN4',
    appId: '1:754077996895:web:b486e8494d508ea367c8ea',
    messagingSenderId: '754077996895',
    projectId: 'flutter-e-commerce-app-91272',
    authDomain: 'flutter-e-commerce-app-91272.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-app-91272.appspot.com',
    measurementId: 'G-ZZJGKLPC94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB19F8TEnozeETHvSwu8wGQIGEWtVOF0Dc',
    appId: '1:754077996895:android:90dfcf5fd6e1d15167c8ea',
    messagingSenderId: '754077996895',
    projectId: 'flutter-e-commerce-app-91272',
    storageBucket: 'flutter-e-commerce-app-91272.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA89t32rhcYD_3VQm-__hD77uiy7w3tEzg',
    appId: '1:754077996895:ios:aa0aa7b4a2fe06a967c8ea',
    messagingSenderId: '754077996895',
    projectId: 'flutter-e-commerce-app-91272',
    storageBucket: 'flutter-e-commerce-app-91272.appspot.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA89t32rhcYD_3VQm-__hD77uiy7w3tEzg',
    appId: '1:754077996895:ios:ec0ebc9211ce410e67c8ea',
    messagingSenderId: '754077996895',
    projectId: 'flutter-e-commerce-app-91272',
    storageBucket: 'flutter-e-commerce-app-91272.appspot.com',
    iosBundleId: 'com.example.ecommerceapp.RunnerTests',
  );
}
